/*******************************************************************************
 * Copyright (c) 2011, 2012 JavaTime project and others
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * 	JavaTime project, Eirik Gronsund - initial implementation
 *******************************************************************************/
package no.javatime.inplace.bundlejobs;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;

import no.javatime.inplace.InPlace;
import no.javatime.inplace.bundlemanager.BundleJobManager;
import no.javatime.inplace.bundleproject.ProjectProperties;
import no.javatime.inplace.msg.Msg;
import no.javatime.inplace.region.closure.CircularReferenceException;
import no.javatime.inplace.region.closure.ProjectSorter;
import no.javatime.inplace.region.manager.BundleTransition;
import no.javatime.inplace.region.manager.BundleTransition.Transition;
import no.javatime.inplace.region.project.BundleProjectState;
import no.javatime.inplace.region.status.BundleStatus;
import no.javatime.inplace.region.status.IBundleStatus;
import no.javatime.inplace.region.status.IBundleStatus.StatusCode;
import no.javatime.util.messages.Category;
import no.javatime.util.messages.TraceMessage;
import no.javatime.util.messages.WarnMessage;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.runtime.jobs.IJobChangeEvent;
import org.eclipse.core.runtime.jobs.IJobManager;
import org.eclipse.core.runtime.jobs.Job;
import org.eclipse.core.runtime.jobs.JobChangeAdapter;
import org.eclipse.osgi.util.NLS;
import org.eclipse.ui.statushandlers.StatusManager;

/**
 * Listen to state changes and report job status in bundle jobs. Bundle status objects added by
 * bundle jobs are reported by this bundle job listener when jobs are done.
 * 
 * @see no.javatime.inplace.region.status.IBundleStatus
 * @see no.javatime.inplace.bundlejobs.JobStatus
 */
public class BundleJobListener extends JobChangeAdapter {

	private long startTime;

	/**
	 * Default constructor for jobs
	 */
	public BundleJobListener() {
		super();
	}

	/**
	 * Calculate and set flush buffer for messages generated by this bundle job.
	 */
	@Override
	public void aboutToRun(IJobChangeEvent event) {
		Job job = event.getJob();
		if (job instanceof BundleJob) {
			// This does not take dependent projects into account
			// int pendingProjects = ((BundleJob) job).pendingProjects();
			// Message.getInstance().setFlushInterval(pendingProjects*5);
		}
	}

	/**
	 * If the option to report on bundle operations is true, a message that the job has started is
	 * forwarded.
	 */
	@Override
	public void running(IJobChangeEvent event) {
		Job job = event.getJob();
		if (job instanceof BundleJob) {
			if (InPlace.get().msgOpt().isBundleOperations()) {
				startTime = System.currentTimeMillis();
			}
		}
	}

	/**
	 * Signal that a bundle job is rescheduled, after waiting for another job.
	 */
	@Override
	public void awake(IJobChangeEvent event) {
		Job job = event.getJob();
		if (job instanceof BundleJob) {
			// if (InPlace.get().msgOpt().isBundleOperations()) {
			// TraceMessage.getInstance().getString("awake_job", job.getName());
			// }
		}
	}

	/**
	 * Signal that a bundle job is scheduled, but is waiting for another job.
	 */
	@Override
	public void sleeping(IJobChangeEvent event) {
		Job job = event.getJob();
		if (job instanceof BundleJob) {
			// if (InPlace.get().msgOpt().isBundleOperations()) {
			// TraceMessage.getInstance().getString("sleep_job", job.getName());
			// }
		}
	}

	/**
	 * Log errors and bundle log bundle jobs.
	 */
	@Override
	public void done(IJobChangeEvent event) {
		final Job job = event.getJob();
		if (job instanceof BundleJob) {
			final BundleJob bundleJob = (BundleJob) job;
			if (InPlace.get().msgOpt().isBundleOperations()) {
				final String endTime = Long.toString(System.currentTimeMillis() - startTime);
				final Collection<IBundleStatus> traceList = bundleJob.getTraceList();
				if (traceList.size() > 0) {
					Runnable trace = new Runnable() {
						public void run() {
							String msg = NLS.bind(Msg.JOB_NAME_TRACE, bundleJob.getName(), endTime);
							IBundleStatus multiStatus = new BundleStatus(StatusCode.INFO, InPlace.PLUGIN_ID, msg);
							for (IBundleStatus status : traceList) {
								multiStatus.add(status);
							}
							InPlace.get().trace(multiStatus);
						}
					};
					trace.run();
				}
			}
			Collection<IBundleStatus> statusList = logCancelStatus(bundleJob);
			if (statusList.size() > 0) {
				String rootMsg = WarnMessage.getInstance().formatString("end_job_root_message",
						bundleJob.getName());
				IBundleStatus multiStatus = new BundleStatus(StatusCode.ERROR, InPlace.PLUGIN_ID, rootMsg);
				for (IBundleStatus status : statusList) {
					multiStatus.add(status);
				}
				// The custom or the standard status handler is not invoked
				// when the workbench is closing. It logs directly to the error log
				StatusManager.getManager().handle(multiStatus, StatusManager.LOG);
			}
			if (InPlace.get().msgOpt().isBundleOperations()) {
				if (Category.DEBUG)
					getBundlesJobRunState(bundleJob);
			}
			schedulePendingOperations(bundleJob);
		}
	}

	private void schedulePendingOperations(BundleJob job) {

		BundleTransition bundleTransition = BundleJobManager.getTransition();
		BundleJob bundleJob = null;

		Collection<IProject> deactivatedProjects = ProjectProperties.getCandidateProjects();
		// This usually comes from a delayed update when activated bundles to resolve depends on
		// deactivated bundles
		Collection<IProject> projectsToActivate = bundleTransition.getPendingProjects(
				deactivatedProjects, Transition.ACTIVATE_PROJECT);
		if (projectsToActivate.size() > 0) {
			bundleJob = new ActivateProjectJob(ActivateProjectJob.activateProjectsJobName,
					projectsToActivate);
			bundleTransition.removePending(projectsToActivate, Transition.ACTIVATE_PROJECT);
			if (InPlace.get().msgOpt().isBundleOperations()) {
				try {
					ProjectSorter projectSorter = new ProjectSorter();
					// Inform about already activated projects that have requirements on deactivated projects
					for (IProject deactivatedProject : projectsToActivate) {
						Collection<IProject> activatedProjects = projectSorter.sortRequiringProjects(
								Collections.<IProject> singletonList(deactivatedProject), true);
						activatedProjects.remove(deactivatedProject);
						if (activatedProjects.size() > 0) {
							String msg = NLS.bind(Msg.IMPLICIT_ACTIVATION_INFO,
									BundleProjectState.formatProjectList(activatedProjects),
									deactivatedProject.getName());
							IBundleStatus status = new BundleStatus(StatusCode.INFO, InPlace.PLUGIN_ID, msg);
							msg = NLS.bind(Msg.DELAYED_RESOLVE_INFO,
									BundleProjectState.formatProjectList(activatedProjects),
									deactivatedProject.getName());
							status.add(new BundleStatus(StatusCode.INFO, InPlace.PLUGIN_ID, msg));
							bundleJob.addTrace(status);
						}
					}
				} catch (CircularReferenceException e) {
				}
			}
			BundleJobManager.addBundleJob(bundleJob, 0);
		}

		Collection<IProject> activatedProjects = BundleProjectState.getNatureEnabledProjects();

		Collection<IProject> projectsToRefresh = bundleTransition.getPendingProjects(activatedProjects,
				Transition.REFRESH);
		if (projectsToRefresh.size() > 0) {
			bundleJob = new RefreshJob(RefreshJob.refreshJobName, projectsToRefresh);
			bundleTransition.removePending(projectsToRefresh, Transition.REFRESH);
			BundleJobManager.addBundleJob(bundleJob, 0);
		}
		Collection<IProject> projectsToDeactivate = bundleTransition.getPendingProjects(
				activatedProjects, Transition.DEACTIVATE);
		if (projectsToDeactivate.size() > 0) {
			bundleJob = new DeactivateJob(DeactivateJob.deactivateJobName, projectsToDeactivate);
			bundleTransition.removePending(projectsToDeactivate, Transition.DEACTIVATE);
			BundleJobManager.addBundleJob(bundleJob, 0);
		}
	}

	/**
	 * If the bundle job has been cancelled, log it
	 * 
	 * @param bundleJob the job that may contain a cancel status
	 * 
	 * @return a copy of the status list with the cancel status removed from the status list or a copy
	 * of the status list if it does not contain any cancel status
	 */
	private Collection<IBundleStatus> logCancelStatus(BundleJob bundleJob) {

		Collection<IBundleStatus> statusList = bundleJob.getStatusList();
		Collection<IBundleStatus> modifiedStatusList = new ArrayList<IBundleStatus>(statusList);
		for (IBundleStatus status : statusList) {
			if (status.hasStatus(StatusCode.CANCEL)) {
				StatusManager.getManager().handle(status, StatusManager.LOG);
				modifiedStatusList.remove(status);
				return modifiedStatusList;
			}
		}
		return statusList;
	}

	/**
	 * Trace that a bundle job is running if the job is in state {@code Job.RUNNING}.
	 * 
	 * @param bundleJob the bundle job to trace
	 */
	private void getBundlesJobRunState(BundleJob bundleJob) {
		IJobManager jobMan = Job.getJobManager();
		Job[] jobs = jobMan.find(BundleJob.FAMILY_BUNDLE_LIFECYCLE);
		for (int i = 0; i < jobs.length; i++) {
			Job job = jobs[i];
			if (job.getState() == Job.RUNNING) {
				TraceMessage.getInstance().getString("running_jobs", job.getName(), bundleJob.getName());
			}
		}
	}
}
